theme: jekyll-theme-architect
# url: https://ina6ra.github.io/zenn-blog
baseurl: /zenn-blog
# permalink: /zenn-blog/:categories/:year-:month-:day-:title:output_ext
# permalink: /zenn-blog/:categories/:year/:month/:day/:title:output_ext
include:
#   - notes/_posts
#   - notes/_blogs
#   - memo
#   - articles
collections_dir: notes
# future: true
collections:
#   posts:
#     output: true
#     permalink: /zenn-blog/:categories/:year/:month/:day/:title:output_ext
  blogs:
    output: true
#     future: true
#     permalink: /zenn-blog/blogs/:path:output_ext
defaults:
  -
    scope:
#       path: ""
      type: blogs
    values:
      layout: default
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
feed:
  path: atom.xml
#   categories:
#     - _posts
#     - memo
