theme: jekyll-theme-architect
permalink: /zenn-blog/:categories/:year-:month-:day-:title:output_ext
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
include:
  - _posts
  - blogs
