theme: jekyll-theme-architect
baseurl: /zenn-blog
# include:
#   - articles
collections_dir: notes
# future: true
collections:
  posts:
    output: true
    permalink: /:slug:output_ext
  blogs:
    output: true
defaults:
  -
    scope:
#       path: ""
      type: blogs
    values:
      layout: default
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
feed:
  path: atom.xml
