title: イネの村
baseurl: /blog
theme: jekyll-theme-architect
# include:
#   - articles
excerpt_separator: <!--more-->
collections_dir: notes
collections:
  posts:
    output: true
    # future: true
    permalink: /:slug:output_ext
  archives:
    output: true
    # permalink: /post/:slug:output_ext
defaults:
  -
    scope:
      # path: ""
      type: archives
    values:
      layout: default
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
feed:
  collections:
    # posts:
    #   path: atom.xml
    archives:
      path: atom.xml
