theme: jekyll-theme-architect
permalink: /zenn-blog/:categories/:year-:month-:day-:title:output_ext
include:
  - _posts
  - note
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
feed:
  path: atom.xml
